version: "3"

networks:
  laravel:

services:
  nginx:
    image: nginx:1.18-alpine
    container_name: nginx
    depends_on:
      - app
      - db
    networks:
      - laravel
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    container_name: app
    depends_on:
      - db
    networks:
      - laravel
    ports:
      - "9000:9000"
    volumes:
      - ./src:/var/www/html

  db:
    image: mysql@sha256:360d1924d86cbf416f2c84687c2037e153080fed932798a73c5c6b4ceb7399e9
    container_name: db
    restart: unless-stopped
    tty: true
    environment:
      - MYSQL_DATABASE=laranote
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    command: "mysqld"
    networks:
      - laravel
    ports:
      - "3308:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD:
    networks:
      - laravel
