version: "3"

networks:
  laranote:

services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    image: nginx:1.18-alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    networks: 
      - laranote
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    image: laranote/app
    container_name: app
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laranote
    depends_on:
        - db

  db:
    image: mysql@sha256:360d1924d86cbf416f2c84687c2037e153080fed932798a73c5c6b4ceb7399e9
    container_name: db
    restart: unless-stopped
    tty: true
    environment:
      - MYSQL_DATABASE=laranote
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    command: "mysqld"
    networks:
      - laranote
    ports:
      - "3308:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD:
    networks:
      - laranote
