version: "3"

networks:
  laravel:

services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: nginx
    depends_on:
      - app
      - db
    networks:
      - laravel
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    container_name: app
    depends_on:
      - db
    networks:
      - laravel
    volumes:
      - ./src:/var/www/html

  db:
    platform: linux/x86_64
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    tty: true
    environment:
      - MYSQL_DATABASE=laranote
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    command: "mysqld"
    networks:
      - laravel
    ports:
      - "3308:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD:
    networks:
      - laravel
