# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
# version: 2
# orbs: 
#   aws-ecr: circleci/aws-ecr@7.0.0
# jobs:
#   build:
#     docker:
#       - image: cimg/node:14.10.1 # the primary container, where your job's commands are run
#     steps:
#       - checkout
#       - run: cp ./src/.env.prod ./src/.env
#       - run:
#           name: Install Docker Compose
#           command: |
#             curl -L https://github.com/docker/compose/releases/download/1.25.3/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
#             chmod +x ~/docker-compose
#             sudo mv ~/docker-compose /usr/local/bin/docker-compose
#       - setup_remote_docker
#       - run: docker-compose build
#       - run: docker images
#       - aws-ecr/ecr-login:
#           account-url: 507651166540.dkr.ecr.ap-northeast-2.amazonaws.com
#           aws-access-key-id: ${AWS_ACCESS_KEY_ID}
#           aws-secret-access-key: ${AWS_SECRET_ACCESS_KEY}
#           region: 'ap-northeast-2'
#       - aws-ecr/push-image:
#           account-url: 507651166540.dkr.ecr.ap-northeast-2.amazonaws.com
#           repo: 'laranote/app'
#           tag: 'latest'

version: '2.1'
orbs:
  aws-cli: circleci/aws-cli@2.0
  aws-ecr: circleci/aws-ecr@7.0.0
jobs:
  build:
    docker:
      - image: cimg/node:14.10.1 # the primary container, where your job's commands are run
    steps:
      - checkout
      - run: cp ./src/.env.prod ./src/.env
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.25.3/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - setup_remote_docker
      - run: docker-compose build
      - run: docker images
  # aws-cli-example:
  #   executor: aws-cli/default
  #   steps:
  #     - checkout
  #     - aws-cli/setup:
  #         profile-name: example
  #     - run: echo "Run your code here"
workflows:
  build-and-push-images:
    jobs:
      - build
      - aws-ecr/ecr-login:
          account-url: 507651166540.dkr.ecr.ap-northeast-2.amazonaws.com
          aws-access-key-id: ${AWS_ACCESS_KEY_ID}
          aws-secret-access-key: ${AWS_SECRET_ACCESS_KEY}
          region: 'ap-northeast-2'
      - aws-ecr/push-image:
          account-url: 507651166540.dkr.ecr.ap-northeast-2.amazonaws.com
          repo: 'laranote/app'
          tag: 'latest'
