version: '2.1'

orbs:
  aws-cli: circleci/aws-cli@2.0
  aws-ecr: circleci/aws-ecr@7.0.0

executors:
  my-executor:
    docker:
      - image: circleci/php:8.0-fpm

commands:
  build-push:
    description: "Build << parameters.repo >> image and push to ECR"
    parameters:
      repo:
        type: string
      dockerfile:
        type: string
    steps:
      - aws-ecr/build-and-push-image:
          dockerfile: << parameters.dockerfile >>
          repo: << parameters.repo >>
          tag: << parameters.tag >>

jobs:
  deploy-app:
    executor: my-executor
    steps:
      - checkout
      - build-push:
          dockerfile: "docker/app/Dockerfile"
          repo: "laranote/app"
          tag: "latest,${CIRCLE_SHA1}"
      - build-push:
          dockerfile: "docker/nginx/Dockerfile"
          repo: "laranote/nginx"
          tag: "latest,${CIRCLE_SHA1}"

workflows:
  version: '2.1'
  laranote:
    jobs:
      - aws-ecr/build-and-push-image:
          dockerfile: "docker/app/Dockerfile"
          repo: "laranote/app"
          tag: 'latest'
          # filters:
          #   branches:
          #     only:
          #       - deployments
      - aws-ecr/build-and-push-image:
          dockerfile: "docker/nginx/Dockerfile"
          repo: "laranote/nginx"
          tag: 'latest'
          # filters:
          #   branches:
          #     only:
          #       - deployments