name: Review on PR

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  openai-review:
    runs-on: ubuntu-latest
    name: Test action
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: OpenAI review released version
        uses: detectiveCrow/ai-review-action@v1.1.3
        with:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LANGUAGE: "korean"
